datacats/datacats

datacats/docker.py

fix for docker 1.6 api change

---

docker/build_images.sh

Change the way we locate ourselves in build_images.sh to be OS X-compatible

---

datacats/cli/create.py
datacats/cli/main.py
datacats/docker.py
datacats/environment.py
datacats/error.py

Error when boot2docker isn't currently up.

---

circle.yml
datacats/cli/purge.py

A --yes/-y option is available if purge is being automated.

Add prompt to datacats purge by default

---

datacats/cli/create.py
datacats/cli/deploy.py
datacats/environment.py
datacats/userprofile.py

More of the same. @wardi , plz CR

Rewrite create commands with Exception handling via Python exceptions

---

datacats/environment.py

Fix address display on boot2docker

---

datacats/cli/manage.py

Check for all containers running before saying we're already running

---

datacats/cli/manage.py
datacats/environment.py

Abstracted check for fully running datacats environment into environment.py

---

datacats/docker.py
datacats/userprofile.py

This addresses [#49](https://github.com/datacats/datacats/issues/49)

Show right message when 'ssh test' is not able to connect to the server

---

circle.yml
datacats/cli/install.py

This also includes it in the CircleCI tests.

Fix #125 by adding an address parameter to load.

---

datacats/cli/less.py
datacats/cli/pull.py

Also allow specifying a --devel option to 'datacats pull' to download all images.

Automatically download datacats/lessc as needed

---

datacats/environment.py

Abstract container naming into a method

---

README.md

Let's get ourselves a pretty documentation badge!

---

datacats/docker.py

Add a hack removing TLS verification

---

circle.yml
datacats/cli/main.py

Fix --version woes

---

datacats/scripts/install_package.sh

Add an error to install for not being able to reach PyPi due to lack of internet connection

---

datacats/cli/create.py
datacats/environment.py

Pass all  keyed arguments from environment.new to environment-__init__

---

datacats/cli/install.py

Raise a DatacatsError instead of printing in install.py

---

datacats/docker.py
datacats/environment.py
datacats/error.py
datacats/userprofile.py

This
1) Addresses and fixes [#146](https://github.com/datacats/datacats/issues/146)
2) Moves all the custom error declarations reused in more than one file to `errors.py`

Figuring out our error handling

---

datacats/cli/create.py
datacats/cli/install.py
datacats/environment.py

Verbose installs

---

datacats/cli/lesscd.py

Make lesscd command work in any directory in or below an environment directory

---

datacats/cli/create.py
datacats/cli/main.py
datacats/environment.py
datacats/error.py

This command is as described in #170

Add a 'reset' command to datacats

---

datacats/environment.py

Check for missing files in source directory

---

datacats/migrate.py

Better error handling for migrations

---

datacats/scripts/check_connectivity.sh

Add better description to DNS error

---

docs/guide.rst

Addresses these kinds of issues: https://github.com/datacats/datacats/issues/186

Attempting to clean up docs on installation instructions

---

datacats/cli/main.py
datacats/error.py

Don't do format in DatacatsError

---

datacats/scripts/install_postgis.sh

not pretty but it should solve the postgres db-create race

wait for postgres in install_postgis script

---

datacats/cli/purge.py

Pass error message via exceptions in purge --delete-environment

---

datacats/cli/create.py
datacats/cli/install.py

Add a quiet parameter to create and install functions so that they can be used programmatically

---

datacats/cli/install.py

Reload all sites after install

---

datacats/task.py

(or any other child section, for that matter)
Fixes #242

Add a check so we don't double up the 'primary' section

---

datacats/environment.py

Address issue with Docker 1.7.0 where entrypoint by string is borked

---

circle.yml
datacats/cli/create.py
datacats/scripts/adjust_devini.py
datacats/scripts/web.sh

As discussed in pull request for datapusher

Fix datapusher woes

---

datacats/cli/main.py
datacats/tests/test_cli_parsing.py

fix shell+paster CLI parsing and add unit tests

---

datacats/environment.py

Run make-config as user so we don't have development.ini owned by root

---

setup.py

Change to directory of current file before getting version for setup.py

---

docker/web/Dockerfile

This has already been pushed to Docker Hub.

Add GDAL to the web image

---

datacats/cli/pull.py
datacats/cli/util.py
datacats/task.py
datacats/tests/test_cli_pull.py
pylintrc
test.sh

Retry pull when it fails

---

datacats/cli/shell.py
test.sh

It would cause an IndexError otherwise.

Make paster command work with zero arguments (print out help)

---

datacats/cli/purge.py
datacats/environment.py
datacats/task.py
test.sh

Add support for format version detection to purge

---

datacats/cli/create.py

Addresses #295 
@deniszgonjanin Can you take a look at this and confirm if it fixes the problem?

Save port before purging on reset

---

datacats/cli/create.py
datacats/cli/install.py
datacats/cli/manage.py
datacats/environment.py
datacats/task.py

remove this parameter as it's confusing.
Addresses #299

Do not provide 'address' parameter to start_ckan

---

datacats/cli/create.py
datacats/cli/manage.py
datacats/environment.py

Fix boot2docker support through introduction of inverted equality symbol

---

datacats/cli/create.py
datacats/cli/install.py

Clean pyc files on clean install, and on reset.

---

datacats/cli/create.py
datacats/docker.py
datacats/environment.py
test.sh

Jack's no initdb merged

---

datacats/docker.py

Drop support for boot2docker

---

docs/faq.rst

Add solution from @deniszgonjanin to FAQ in docs on how to modify local images.

Fix #210 by adding solution to FAQ in docs

---

datacats/cli/create.py
datacats/cli/pull.py

ckan:2.3 has a critical error that is resolved in 2.4 https://github.com/datacats/datacats/issues/334

Default to ckan:2.4 image
